const callGlobal = (name, ...args) => {
  if (typeof window !== "undefined" && typeof window[name] === "function") return window[name](...args);
};

export default function Pages() {
  return (
    <div id="main">
      {/* Dashboard */}
      <div className="page active" id="page-dashboard">
        <div className="page-header">
          <div className="page-title">Panel Principal</div>
          <div className="page-sub" id="dash-sub">—</div>
        </div>
        <div className="course-banner" id="dash-banner"></div>
        <div className="stat-grid" id="dash-stats"></div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 320px",gap:"18px",marginBottom:"18px"}}>
          <div className="card"><div className="card-header"><div className="card-title">Distribución de Calificaciones</div></div><div className="card-body"><canvas id="dash-chart-distribution" height="220"></canvas></div></div>
          <div className="card"><div className="card-header"><div className="card-title">Notas por Estudiante</div></div><div className="card-body"><canvas id="dash-chart-students" height="220"></canvas></div></div>
          <div className="card"><div className="card-header"><div className="card-title">Resumen</div></div><div className="card-body" style={{display:"flex",flexDirection:"column",gap:"14px"}}><div style={{textAlign:"center"}}><canvas id="dash-chart-pie" width="160" height="160"></canvas><div id="dash-pie-label" style={{fontSize:".8rem",color:"var(--gray-500)",marginTop:"8px"}}></div></div><div id="dash-ra-summary"></div></div></div>
        </div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"18px",marginBottom:"18px"}}>
          <div className="card"><div className="card-header"><div className="card-title">Progreso por Componente</div></div><div className="card-body" id="dash-comp-progress"></div></div>
          <div className="card"><div className="card-header"><div className="card-title">Actividad Reciente</div></div><div className="card-body" id="dash-recent-activity"></div></div>
        </div>
        <div className="card">
          <div className="card-header"><div className="card-title">Nómina de Estudiantes</div></div>
          <div style={{overflowX:"auto"}}>
            <table className="data"><thead><tr><th style={{width:"40px"}}>#</th><th>Estudiante</th><th>Nota</th><th>Estado</th></tr></thead><tbody id="dash-student-body"></tbody></table>
          </div>
        </div>
      </div>

      {/* Configuración */}
      <div className="page" id="page-configuracion"><div className="page-header"><div className="page-title">Configuración</div><div className="page-sub">Configure los parámetros de la asignatura, RAC, RAAU y actividades</div></div><div id="cfg-wizard"><div className="stepper" id="cfg-stepper"></div>
      <div id="cfg-step-0"><div className="card"><div className="card-header"><div className="card-title">Información de la Asignatura</div></div><div className="card-body">
      <div className="form-grid"><div className="form-group"><label className="form-label">Período Académico</label><input className="form-input" id="cfg-periodo" placeholder="Ej: SEPTIEMBRE 2025 - FEBRERO 2026"/></div><div className="form-group"><label className="form-label">Facultad / Sede</label><input className="form-input" id="cfg-facultad" defaultValue="SEDE ORELLANA" readOnly/></div></div>
      <div className="form-grid-3"><div className="form-group"><label className="form-label">Carrera</label><select className="form-select" id="cfg-carrera" onChange={() => callGlobal("onCarreraChange")}><option value="">-- Seleccione la carrera --</option><option value="TECNOLOGÍAS DE LA INFORMACIÓN">Tecnologías de la Información</option><option value="AMBIENTAL">Ambiental</option><option value="AGRONOMÍA">Agronomía</option><option value="ZOOTECNIA">Zootecnia</option><option value="TURISMO">Turismo</option><option value="DERECHO">Derecho</option></select></div><div className="form-group"><label className="form-label">PAO (Semestre)</label><select className="form-select" id="cfg-pao" onChange={() => callGlobal("onPaoChange")} disabled><option value="">-- Seleccione PAO --</option></select></div><div className="form-group"><label className="form-label">Asignatura</label><select className="form-select" id="cfg-asignatura" disabled onChange={() => callGlobal("onAsignaturaChange")}><option value="">-- Seleccione primero Carrera y PAO --</option></select></div></div>
      <div className="form-grid"><div className="form-group"><label className="form-label">Docente</label><input className="form-input" id="cfg-docente" placeholder="Nombre del docente"/></div><div className="form-group"><label className="form-label">Aporte / Corte</label><select className="form-select" id="cfg-aporte" defaultValue="FIN DE CICLO"><option value="MEDIO CICLO">MEDIO CICLO</option><option value="FIN DE CICLO">FIN DE CICLO</option><option value="RECUPERACIÓN">RECUPERACIÓN</option></select></div></div>
      </div></div></div>
      <div id="cfg-step-1" style={{display:"none"}}><div className="card"><div className="card-header"><div className="card-title">Resultados de Aprendizaje de la Carrera (RAC)</div></div><div className="card-body"><div className="info-box"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="10"/><line x1="12" y1="16" x2="12" y2="12"/><line x1="12" y1="8" x2="12.01" y2="8"/></svg><p>Seleccione los RAC que se trabajarán en esta asignatura. Se seleccionan automáticamente según el mapeo.</p></div><div id="cfg-rac-title" style={{fontSize:".85rem",fontWeight:600,color:"var(--navy)",marginBottom:"12px"}}></div><div id="cfg-rac-list"></div></div></div></div>
      <div id="cfg-step-2" style={{display:"none"}}><div className="card"><div className="card-header"><div className="card-title">Resultados de Aprendizaje de la Asignatura (RAAU)</div></div><div className="card-body"><div className="info-box"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="10"/><line x1="12" y1="16" x2="12" y2="12"/><line x1="12" y1="8" x2="12.01" y2="8"/></svg><p>Los RAAU se cargan automáticamente desde RAC. Puede editarlos o agregar más.</p></div><div id="cfg-selected-summary" style={{marginBottom:"12px"}}></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"12px"}}><span style={{fontSize:".85rem",fontWeight:600,color:"var(--navy)"}}>RAAU definidos</span><button className="btn btn-sm btn-primary" onClick={() => callGlobal("addRAAU")}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{width:"13px",height:"13px"}}><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg> Agregar RAAU</button></div><div id="cfg-raau-list"></div></div></div></div>
      <div id="cfg-step-3" style={{display:"none"}}><div className="card"><div className="card-header"><div className="card-title">Actividades de Evaluación</div></div><div className="card-body"><div className="info-box"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="10"/><line x1="12" y1="16" x2="12" y2="12"/><line x1="12" y1="8" x2="12.01" y2="8"/></svg><p>Nota sobre 10: ACD (3.5 pts) + APEX (3.5 pts) + AAUT (3.0 pts). Se requieren al menos 2 actividades por componente.</p></div><div id="cfg-activities-panels"></div><div id="cfg-activities-summary" style={{marginTop:"16px",padding:"14px",background:"var(--gray-50)",borderRadius:"var(--radius)",display:"none"}}><div style={{fontSize:".82rem",fontWeight:600,color:"var(--gray-700)",marginBottom:"8px"}}>Resumen de Actividades</div><div id="cfg-activities-summary-content"></div></div></div></div></div>
      <div style={{display:"flex",justifyContent:"space-between",marginTop:"20px"}}><button className="btn btn-ghost" id="cfg-prev" onClick={() => callGlobal("cfgPrev")} style={{display:"none"}}>← Anterior</button><div></div><div style={{display:"flex",gap:"8px"}}><button className="btn btn-primary" id="cfg-next" onClick={() => callGlobal("cfgNext")}>Siguiente →</button><button className="btn btn-success" id="cfg-save" onClick={() => callGlobal("cfgSave")} style={{display:"none"}}>Guardar para finalizar</button></div></div>
      <div className="card" style={{marginTop:"18px"}}>
        <div className="card-header"><div className="card-title">Configuraciones guardadas</div></div>
        <div className="card-body" id="cfg-saved-configs"></div>
      </div>
      </div>
      <div id="cfg-managed-section" style={{display:"none"}}></div>
      </div>

      {/* Estudiantes */}
      <div className="page" id="page-estudiantes"><div className="page-header"><div className="page-title">Estudiantes</div><div className="page-sub" id="est-sub">0 estudiantes matriculados</div></div><div className="stat-grid" id="est-stats" style={{gridTemplateColumns:"repeat(3,1fr)",marginBottom:"18px"}}></div><div className="card"><div className="card-header"><div className="card-title" id="est-table-title">Nómina</div><div style={{display:"flex",gap:"8px",alignItems:"center"}}><div className="search-wrap"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg><input className="search-input" id="est-search" placeholder="Buscar por nombre, cedula (con/sin -) o codigo..." onInput={() => callGlobal("renderStudentTable")}/></div><button className="btn btn-edit btn-sm" id="est-oasis-btn" onClick={() => callGlobal("showOasisImport")}>Actualizar</button><button className="btn btn-primary btn-sm" onClick={() => callGlobal("exportStudentsPDF")}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{width:"13px",height:"13px"}}><polyline points="6 17 6 21 18 21 18 17"/><line x1="12" y1="3" x2="12" y2="17"/><line x1="5" y1="10" x2="12" y2="3"/><line x1="19" y1="10" x2="12" y2="3"/></svg> Exportar PDF</button></div></div><div id="est-import-status" style={{padding:"0 16px 12px",fontSize:".78rem",color:"var(--gray-500)"}}></div><div style={{overflowX:"auto"}}><table className="data"><thead><tr><th style={{width:"40px"}}>#</th><th>Código</th><th>Cédula</th><th>Apellidos</th><th>Nombres</th><th>Nota</th><th>Estado</th><th style={{width:"100px"}}>Acciones</th></tr></thead><tbody id="est-body"></tbody></table></div></div></div>

      {/* Calificaciones */}
      <div className="page" id="page-calificaciones"><div className="page-header"><div className="page-title">Registro de Calificaciones</div><div className="page-sub" id="cal-sub">—</div></div><div className="comp-bar" id="cal-legend"></div><div className="card" style={{marginBottom:"18px"}}><div className="card-header"><div className="card-title">Progreso</div><div style={{display:"flex",alignItems:"center",gap:"12px",flex:1,marginLeft:"20px"}}><div className="progress-bar" style={{flex:1}}><div className="progress-fill" id="cal-progress-fill" style={{width:"0%",background:"var(--espoch-green)"}}></div></div><span id="cal-progress-pct" style={{fontSize:".75rem",fontWeight:600,color:"var(--gray-600)"}}>0%</span><span id="cal-progress-label" style={{fontSize:".72rem",color:"var(--gray-400)"}}>0/0 notas</span></div><button className="btn btn-success btn-sm" id="cal-save-btn" onClick={() => callGlobal("calSave")}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"/><polyline points="17 21 17 13 7 13 7 21"/><polyline points="7 3 7 8 15 8"/></svg> Guardar</button><button className="btn btn-primary btn-sm" onClick={() => callGlobal("exportGradesPDF")}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{width:"13px",height:"13px"}}><polyline points="6 17 6 21 18 21 18 17"/><line x1="12" y1="3" x2="12" y2="17"/><line x1="5" y1="10" x2="12" y2="3"/><line x1="19" y1="10" x2="12" y2="3"/></svg> Exportar</button><button className="btn btn-edit btn-sm" onClick={() => callGlobal("showGradesQR")}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{width:"13px",height:"13px"}}><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/></svg> QR</button></div></div><div id="cal-grid" className="card"><div className="card-body" id="cal-grid-body" style={{padding:0,overflowX:"auto"}}></div></div></div>

      {/* Reporte */}
      <div className="page" id="page-reporte"><div className="page-header"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div className="page-title">Reporte Final</div><div className="page-sub">Evaluación formativa y sumativa para alcanzar los resultados de aprendizaje</div></div><div style={{display:"flex",gap:"8px"}}><button className="btn btn-primary" onClick={() => callGlobal("printDetailedReport")}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{width:"14px",height:"14px"}}><polyline points="6 9 6 2 18 2 18 9"/><path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><rect x="6" y="14" width="12" height="8"/></svg> Imprimir reporte detallado</button></div></div></div><div className="stat-grid" id="rep-stats" style={{gridTemplateColumns:"repeat(4,1fr)",marginBottom:"18px"}}></div><div className="rep-layout"><div className="card"><div className="card-header"><div className="card-title">Reporte Detallado</div></div><div className="card-body" style={{padding:0}} id="rep-printable"></div></div><div><div className="card" style={{marginBottom:"18px"}}><div className="card-header"><div className="card-title">Distribución</div></div><div className="card-body"><div className="dist-chart" id="rep-dist"></div></div></div></div></div></div>

      {/* Coordinación */}
      <div className="page" id="page-coordinacion"><div className="page-header"><div className="page-title">Panel de Coordinación</div><div className="page-sub">Monitoreo de aplicación RAC/RAAU y mapeo curricular</div></div><div id="coord-content"></div></div>
      <div className="page" id="page-coord-asignaturas"><div className="page-header"><div className="page-title">Asignaturas</div><div className="page-sub">Asignación docente y seguimiento por asignatura</div></div><div id="coord-content-asignaturas"></div></div>
      <div className="page" id="page-coord-rac"><div className="page-header"><div className="page-title">RAC</div><div className="page-sub">Gestión de resultados de aprendizaje de carrera</div></div><div id="coord-content-rac"></div></div>
      <div className="page" id="page-coord-raau"><div className="page-header"><div className="page-title">RAAU</div><div className="page-sub">Gestión de resultados de aprendizaje de asignatura</div></div><div id="coord-content-raau"></div></div>
      <div className="page" id="page-coord-docentes"><div className="page-header"><div className="page-title">Docentes por Asignatura</div><div className="page-sub">Monitoreo y matriz docente/asignaturas</div></div><div id="coord-content-docentes"></div></div>

      {/* Consultas */}
      <div className="page" id="page-consulta-sede"><div className="page-header"><div className="page-title">Sede Orellana</div><div className="page-sub">Explorador académico por carrera, PAO, materias y docentes</div></div><div id="consulta-sede-content"></div></div>
      <div className="page" id="page-consulta-informacion"><div className="page-header"><div className="page-title">Información General</div><div className="page-sub">Período actual, carreras activas y estado del sistema</div></div><div id="consulta-info-content"></div></div>
      <div className="page" id="page-consulta-estudiante"><div className="page-header"><div className="page-title">Datos de Estudiante</div><div className="page-sub">Consultar información completa del estudiante por cédula</div></div><div id="consulta-est-content"></div></div>

      <footer className="app-footer">ESPOCH · Sistema de Calificaciones · © 2026</footer>
    </div>
  );
}